name: TEST WEB API AUTOMATION JAVA MINI PROJECT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: C:\\Users\\VICTUS\\IdeaProjects\\MiniProjectCICDPipeline
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test API Mini Project
        run: |
          cd CICD-Pipeline-MiniProject
          mvn verify
          working-directory: ./CICD-Pipeline-MiniProject

#        working-directory: C:\\Users\\VICTUS\\IdeaProjects\\MiniProjectCICDPipeline