jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: C:\\Users\\VICTUS\\IdeaProjects\\MiniProjectCICDPipeline
  test:
    name: TEST WEB API AUTOMATION MINI PROJECT
    runs-on: ubuntu-latest
    steps:
      - name: Test API Mini Project
        run: mvn clean verify
        working-directory: C:\\Users\\VICTUS\\IdeaProjects\\MiniProjectCICDPipeline
